num1 = int (input("Enter your  first number:  "))
num2 = int(input("Enter your second number:  "))

print("Addition =", num1 + num2)
print("Substraction =" , num1 - num2)
print("Multiplication =", num1 * num2)
print("Division =", num1 / num2)
print("Remainder =", num1 % num2)
print("Floor Devision =", num1 // num2)
print("Power =", num1 ^ num2)